name: game deployment

on:
  push:
    branch:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: HTML validation
#        uses: validator/action@v2
#        with:
#          files: "*.html"
#
#      - name: JS Syntax Check
#        uses: reviewdog/action-eslint@v2
#        with:
#          github_token: ${{ secrets.TOKEN }}
#          eslint_flags: "index.html" # 检查内联JS

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
